In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,models

In [4]:
import tensorflow as tf
print(tf.__version__)

2.18.0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [6]:
from google.colab import files
uploaded = files.upload()

Saving fake_or_real_news.csv to fake_or_real_news.csv

In [7]:
df=pd.read_csv('fake_or_real_news.csv')
df.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [8]:
df.isna().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [9]:
x=df['text'].astype(str).values
y=df['label'].map({'FAKE':0,'REAL':1})
y

0       0
1       0
2       1
3       0
4       1
       ..
6330    1
6331    0
6332    0
6333    1
6334    1
Name: label, Length: 6335, dtype: int64

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
tfid=TfidfVectorizer(max_features=5000,stop_words='english')
X_train_tfidf = tfid.fit_transform(x_train).toarray()
X_test_tfidf = tfid.transform(x_test).toarray()

In [13]:
model = models.Sequential([
    layers.Dense(128, activation='relu', input_shape=(X_train_tfidf.shape[1],)),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(1, activation='sigmoid')
])
model.summary()
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

model.fit(X_train_tfidf, y_train, epochs=10, batch_size=32)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │       640,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 648,449 (2.47 MB)

 Trainable params: 648,449 (2.47 MB)

 Non-trainable params: 0 (0.00 B)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │       640,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 648,449 (2.47 MB)

 Trainable params: 648,449 (2.47 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7336 - loss: 0.5290
Epoch 2/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9652 - loss: 0.1122
Epoch 3/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9904 - loss: 0.0360
Epoch 4/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9972 - loss: 0.0147
Epoch 5/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0052
Epoch 6/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9997 - loss: 0.0028
Epoch 7/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 1.0000 - loss: 0.0018
Epoch 8/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 1.0000 - loss: 8.6843e-04
Epoch 9/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 8.5787e-04
Epoch 10/10
159/159 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.5673e-04

In [14]:
model.evaluate(X_test_tfidf,y_test)
y_pred=model.predict(X_test_tfidf)

40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9350 - loss: 0.3054
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [33]:
# Correct prediction code:
user_input = input("Enter news article text: ")
user_idf=tfid.transform([user_input]).toarray()
prediction = model.predict(user_idf)
print("Prediction:", "REAL" if prediction[0] > 0.5 else "FAKE")

Enter news article text: Apple announced that iOS 17 will be released globally on September 18, featuring new privacy tools and a redesigned messaging app. The update will be available for iPhones from version X and later
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Prediction: FAKE

In [26]:

label_counts = df['label'].value_counts()
print(label_counts)

label
REAL    3171
FAKE    3164
Name: count, dtype: int64

In [29]:

from sklearn.feature_extraction.text import CountVectorizer

real_words = ' '.join(df[df['label']=='REAL']['text']).split()
fake_words = ' '.join(df[df['label']=='FAKE']['text']).split()

print("Top REAL words:", pd.Series(real_words).value_counts().head(10))
print("Top FAKE words:", pd.Series(fake_words).value_counts().head(10))

Top REAL words: the     143771
to       78281
of       68271
a        62286
and      59850
in       52541
that     36925
is       26065
for      25380
on       22946
Name: count, dtype: int64
Top FAKE words: the     114516
of       60050
to       58445
and      51569
a        40215
in       35978
that     27347
is       25886
for      18092
on       14678
Name: count, dtype: int64

In [28]:

y_pred_binary = (y_pred > 0.5).astype(int)

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred_binary, target_names=['REAL', 'FAKE']))


print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_binary))

              precision    recall  f1-score   support

        REAL       0.94      0.93      0.93       628
        FAKE       0.93      0.94      0.93       639

    accuracy                           0.93      1267
   macro avg       0.93      0.93      0.93      1267
weighted avg       0.93      0.93      0.93      1267

Confusion Matrix:
[[581  47]
 [ 40 599]]